name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  # manual dispatch to test if pipes are running
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Generate static files
      env:
        NEON_CONNECTION_STRING: ${{ secrets.NEON_CONNECTION_STRING }}
      run: npm run generate
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run tests
      run: npm run test
    
    - name: Build application
      run: npm run build

    - name: Publish script versions
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        PUBLISH_SECRET: ${{ secrets.PUBLISH_SECRET }}
      run: node build-scripts/publish-scripts.js

# test if Dockerfile *can* build successfully/prevent someone from breaking it
    - name: Create Docker Image
      run: docker build -t tweakforge .
